# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "kse-file-manager"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "kse-file-manager"
region = "ap-northeast-1"
profile = "default"
parameter_overrides = "SlackSigningSecret=\"5137faece93c075f8d733ed9ce5159be\" SlackApiToken=\"xoxb-9015532818849-9029934412247-O6Ztc0wprcSMKKiWaeqwEl1R\" BucketName=\"kse-file\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
