AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kse-file-manager

  Sample SAM Template for kse-file-manager

Globals:
  Function:
    Timeout: 3
    MemorySize: 512

Parameters:
  SlackSigningSecret:
    Type: String
    Description: Slack Signing Secret
  SlackApiToken:
    Type: String
    Description: Slack Api Token
  BucketName:
    Type: String
    Description: S3 Bucket Name

Resources:
  FileListEnqueue:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: file_manager/file_list/enqueue/
      Handler: app.lambda_handler
      Runtime: ruby3.4
      Timeout: 3
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref MessageQueue
      Architectures:
        - x86_64
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
          QUEUE_NAME: !Ref MessageQueue
      Events:
        FileList:
          Type: Api
          Properties:
            Path: /file_manager/file_list
            Method: post
  # FileListDequeue:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: file_manager/file_list/dequeue/
  #     Handler: app.lambda_handler
  #     Runtime: ruby3.2
  #     Timeout: 10
  #     Policies:
  #       - S3ReadPolicy:
  #           BucketName: !Ref FileBucket
  #     Architectures:
  #       - x86_64
  #     Environment:
  #       Variables:
  #         BUCKET_NAME: !Ref FileBucket
  #         SLACK_API_TOKEN: !Ref SlackApiToken
  #     Events:
  #       Dequeue:
  #         Type: SQS
  #         Properties:
  #           Queue: !GetAtt MessageQueue.Arn
  MessageQueue:
    Type: AWS::SQS::Queue
  MessageQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: !Ref MessageQueue
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 'SQS:*'
            Resource: !GetAtt MessageQueue.Arn
      Queues:
        - !Ref MessageQueue
  FileBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  FileManageApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/file_manager/'
